### ISSUE TITLE
New line replace string?

### ISSUE THREAD

**Issue by Czab1** [ThunderGemios10/MotdManager-Reloaded#2]
Hello,
I was wondering if it's possible to add a replace string for a new line. Example:

- My Server! %n Join Today!

Where %n is the replace string for a new line.
Thanks!

**Comment by ThunderGemios10** [comment]
Use `/n` for replace string.

**Comment by ThunderGemios10** [comment]
@Czab1 Hmm, That's odd... Is the plugin updated?
